<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<h1><?php echo $this->__('Account Overview') ?></h1>

<h2><?php echo $this->__('Hello %s, it\'s nice to see you!', $this->htmlEscape( Mage::getSingleton('customer/session')->getCustomer()->getFirstname() ) ); ?></h2>
<?php /*echo $this->__('Hello %s!', $this->htmlEscape($this->getCustomerName()))*/ ?>