<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.4
 */
?>

<?php
$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
?>

<?php if ($_product->isSaleable() && count($_attributes)):?>
	<dl class="configurable-options">
		<?php foreach($_attributes as $_attribute): ?>
			<dt><label for="attribute<?php echo $_attribute->getAttributeId() ?>"><?php echo $_attribute->getLabel() ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label></dt>
			<dd>
				<select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
					<option><?php echo $this->__('Select...') ?></option>
				</select>
			</dd>
		<?php endforeach; ?>
	</dl>
	
	<script type="text/javascript">
		var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
	</script>
<?php endif;?>
