<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.2
 */
?>

<div class="block">
	<h1><?php echo $this->__('Review Order') ?></h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<?php if ($this->getShippingAddress()): ?>
		<div class="callout">
			<h2><?php echo $this->__('Shipping Information') ?></h2>
			
			<div class="grid">
				<div class="grid_6 alpha">
					<div class="shipping-address">
						<h3><?php echo $this->__('Shipping Address') ?></h3>
						<p class="address-entry"><?php echo $this->renderAddress($this->getShippingAddress())?></p>
						
						<?php if ($this->getCanEditShippingAddress()):?>
							<p><a class="faux-button" href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Change') ?></a></p>
						<?php endif; ?>
					</div>
				</div>
				
				<div class="grid_6 omega">
					<div class="shipping-method">
						<h3><?php echo $this->__('Shipping Method') ?></h3>
						
						<?php if ($this->getCanEditShippingMethod() || !$this->getCurrentShippingRate()):?>
							<?php if ($groups = $this->getShippingRateGroups()):?>
								<?php $currentRate = $this->getCurrentShippingRate(); ?>
								
								<form method="post" id="shipping_method_form" action="<?php echo $this->escapeHtml($this->getShippingMethodSubmitUrl()) ?>">
									<select name="shipping_method" id="shipping_method" style="width:250px;" class="required-entry">
										<?php if (!$currentRate): ?>
											<option value=""><?php echo $this->__('Please select a shipping method...') ?></option>
										<?php endif; ?>
										
										<?php foreach ($groups as $code => $rates): ?>
											<optgroup label="<?php echo $this->getCarrierName($code) ?>" style="font-style:normal;">
												<?php foreach ($rates as $rate): ?>
													<option value="<?php echo $this->renderShippingRateValue($rate)?>"<?php echo ($currentRate === $rate) ? ' selected="selected"' : '' ;?>>
														<?php echo $this->renderShippingRateOption($rate)?>
													</option>
												<?php endforeach; ?>
											</optgroup>
										<?php endforeach;?>
									</select>
									
									<p class="actions">
										<button id="update_shipping_method_submit" type="submit" class="button"><span><span><?php echo $this->__('Update Shipping Method') ?></span></span></button>
									</p>
								</form>
							<?php else: ?>
								<p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
							<?php endif;?>
						<?php else: ?>
							<p><?php echo $this->renderShippingRateOption($this->getCurrentShippingRate())?></p>
						<?php endif; ?>
					</div>
				</div>
			</div>
		</div>
	<?php endif; ?>
	
	<div class="callout">
		<h2><?php echo $this->__('Billing Information') ?></h2>
		
		<div class="grid">
			<div class="grid_6 alpha">
				<div class="billing-address">
					<h3><?php echo $this->__('Billing Address') ?></h3>
					<p class="address-entry"><?php echo $this->renderAddress($this->getBillingAddress()) ?></p>
					<p><?php echo $this->__('Payer Email: %s', $this->getBillingAddress()->getEmail()) ?></p>
				</div>
			</div>
			
			<div class="grid_6 omega">
				<div class="billing-method">
					<h3><?php echo $this->__('Payment Method') ?></h3>
					<p><?php echo $this->escapeHtml($this->getPaymentMethodTitle()) ?></p>
					<?php if($this->getEditUrl()):?><p><a class="faux-button" href="<?php echo $this->getEditUrl() ?>"><?php echo $this->__('Change') ?></a></p><?php endif; ?>
				</div>
			</div>
		</div>
	</div>
	
	<div class="callout">
		<h2><?php echo $this->__('Items In Your Cart') ?></h2>
			
		<div class="cart-items">
			<p><a class="faux-button" href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
			
			<div id="details-reload">
				<?php echo $this->getChildHtml('details') ?>
			</div>
		</div>
	</div>
	
	<form method="post" id="order_review_form" action="<?php echo $this->getPlaceOrderUrl() ?>">
	    <?php echo $this->getChildHtml('agreements'); ?>
	    
		<div class="buttons-set buttons-set-order" id="review-buttons-container">
			<button type="button" id="review_button" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
			<button type="button" id="review_submit" value="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
			
			<div><span class="please-wait opc-ajax-loading" id="review-please-wait" style="display:none;"><?php echo $this->__('Submitting order...') ?></span></div>
		</div>
	</form>
</div>

<script type="text/javascript">
//<![CDATA[
// submit buttons are not needed when submitting with ajax
$('review_submit').hide();
if ($('update_shipping_method_submit')) {
	$('update_shipping_method_submit').hide();
}

<?php if ($this->getUseAjax()):?>
    OrderReviewController.prototype._submitOrder = function() {
        if (this._canSubmitOrder) {
            if (this._pleaseWait) {
                this._pleaseWait.show();
            }
            new Ajax.Request(this.form.action, {
                parameters: {isAjax: 1, method: 'POST'},
                onSuccess: function(transport) {
                    try{
                        response = eval('(' + transport.responseText + ')');
                    } catch (e) {
                        response = {};
                    }
                    if (response.redirect) {
                        setLocation(response.redirect);
                        return;
                    }
                    if (response.success) {
                        setLocation('<?php echo $this->getSuccessUrl()?>');
                        return;
                    } else {
                        var msg = response.error_messages;
                        if (typeof(msg)=='object') {
                            msg = msg.join("\n");
                        }
                        if (msg) {
                            $('review-please-wait').hide();
                            alert(msg);
                            return;
                        }
                    }
                    $('review-please-wait').hide();
                    alert('<?php echo $this->jsQuoteEscape($this->__('Unknown Error. Please try again later.')); ?>');
                    return;
                },
                onFailure: function(){
                    alert('<?php echo $this->jsQuoteEscape($this->__('Server Error. Please try again.')) ?>');
                    $('review-please-wait').hide();
                }
            });
        }
    }
<?php endif ?>

PayPalExpressAjax = new OrderReviewController($('order_review_form'), $('review_button'),
	$('shipping_method'), $('shipping_method_form'), 'details-reload'
);
PayPalExpressAjax.addPleaseWait($('review-please-wait'));
//]]>
</script>
