<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<h2>
	<?php echo $this->__('Discount Code') ?>
	<span class="note"><?php echo $this->__('Type a discount code if you have one.') ?></span>
</h2>

<form id="coupon-form" class="scaffold custom" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
	<input type="hidden" id="remove_coupon" name="remove" value="0" />
	
	<ul class="struts">
		<li>
			<label for="coupon_code"><?php echo $this->__('Code') ?></label>
			<input type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
		</li>
	</ul>
	
	<button onclick="couponForm.submit(false)"><?php echo $this->__('Apply') ?></button>
	
	<?php if(strlen($this->getCouponCode())): ?>
		<a class="alt-action" href="#" onclick="couponForm.submit(true)"><?php echo $this->__('Remove Code') ?></a>
	<?php endif;?>
</form>

<script type="text/javascript">
	//<![CDATA[
	var couponForm = new VarienForm('coupon-form');
	couponForm.submit = function (isRemove) {
		if (isRemove) {
			$('coupon_code').removeClassName('required-entry');
			$('remove_coupon').value = "1";
		} else {
			$('coupon_code').addClassName('required-entry');
			$('remove_coupon').value = "0";
		}
		return VarienForm.prototype.submit.bind(couponForm)();
	}
	//]]>
</script>