<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.4
 */
?>

<div class="block">
	<h1><?php echo $this->__('My Cart') ?></h1>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<div class="cart-no-items">
		<h2><?php echo $this->__('Your cart is empty.') ?></h2>
		<p><?php echo $this->__('Try a search, browse the categories, or see our') ?> <a href="<?php echo $this->getContinueShoppingUrl(); ?>"><?php echo $this->__('featured products') ?></a>.</p>
	</div>
</div>
