<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<?php if($_heading = $this->getContentHeading()): ?>
	<div class="block">
		<h1><?php echo $_heading; ?></h1>
	</div>
<?php endif; ?>
