<?php $lang = Mage::helper("klarnaPaymentModule/lang");; ?>
<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/base/default/klarna/logo/klarna_logo.png'; ?>" style="margin-top: 5px; margin-bottom: 10px;" alt="Klarna" />
<?php if ($this->getTransactionNumber()): ?>
<p><b><?php echo $lang->fetch($this->getTransactionLabel(), $country); ?>:</b> <?php echo $this->getTransactionNumber(); ?></p>
<?php endif; ?>