<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<div id="popular-searches" class="callout">
	<h2><?php echo $this->__('Popular Searches') ?></h2>

	<?php if( sizeof($this->getTerms()) > 0 ): ?>
		<ul class="tags-list">
			<?php foreach ($this->getTerms() as $_term): ?>
				<li><a href="<?php echo $this->getSearchUrl($_term) ?>" <?php /*style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"*/ ?>><?php echo $this->htmlEscape($_term->getName()) ?></a></li>
			<?php endforeach; ?>
		</ul>
	<?php else: ?>
		<p><?php echo $this->__('No search terms available.'); ?></p>
	<?php endif; ?>
</div>
