<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<div class="dashboard">
	<?php echo $this->getChildHtml('hello') /* customer/account/dashboard/hello.phtml */ ?>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<?php echo $this->getChildHtml('info') /* customer/account/dashboard/info.phtml */ ?>
	<?php echo $this->getChildHtml('address') /* customer/account/dashboard/address.phtml */ ?>
	<?php /*echo $this->getChildHtml('newsletter')*/ /* customer/account/dashboard/newsletter.phtml */  /* does not work */ ?>
	<?php echo $this->getChildHtml('top') /* sales/order/recent.phtml */ ?>
	<?php echo $this->getChildHtml('info1')  /* review/customer/recent.phtml */ ?>
	<?php echo $this->getChildHtml('info2')  /* tag/customer/recent.phtml */ ?>
</div>
