<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php 
/**
 * @see Mage_Page_Block_Template_Container
 */
?>

<div class="block">
    <h1><?php echo $this->getTitle() ?></h1>
</div>

<?php echo $this->getChildHtml() ?>
