<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.9
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>

<div class="block">
	<h1><?php echo $this->__('Create An Account') ?></h1>
	
	<?php echo $this->getChildHtml('form_fields_before')?>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="grid">
	<div class="grid_7">
		<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="register-form" class="scaffold">
			<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
			<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
			
			<h3><?php echo $this->__('Personal Info') ?></h3>
			
			<ul class="struts">
				<?php /*  see: /template/customer/widget/name.phtml  */ ?>
				<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->toHtml() ?>
			
				<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
				<?php if ($_dob->isEnabled()): ?>
					<li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
				<?php endif ?>
				
				<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
				<?php if ($_taxvat->isEnabled()): ?>
					<li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
				<?php endif ?>
				
				<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
				<?php if ($_gender->isEnabled()): ?>
					<li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
				<?php endif ?>
			</ul>
			
			<?php if($this->getShowAddressFields()): ?>
				<input type="hidden" name="create_address" value="1" />
				
				<h3><?php echo $this->__('Address Info') ?></h3>
				
				<ul class="struts">
					<?php /*<li>
						<label for="company"><?php echo $this->__('Company') ?></label>
						<input type="text" id="company" name="company" value="<?php echo $this->htmlEscape($this->getFormData()->getCompany()) ?>" />
					</li>*/ ?>
					
					<li>
						<label for="telephone"><?php echo $this->__('Phone') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<input type="text" id="telephone" name="telephone" value="<?php echo $this->htmlEscape($this->getFormData()->getTelephone()) ?>" class="required-entry" />
					</li>
					
					<li>
						<label for="street_1"><?php echo $this->__('Street Address') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
					</li>
					
					<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
						<li>
							<input type="text" id="street_<?php echo $_i?>" name="street[]" value="<?php echo $this->htmlEscape($this->getFormData()->getStreet($_i)) ?>" />
						</li>
					<?php endfor ?>
					
					<li>
						<label for="city"><?php echo $this->__('City') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<input type="text" id="city" name="city" value="<?php echo $this->htmlEscape($this->getFormData()->getCity()) ?>"  class="required-entry" />
					</li>
					
					<li>
						<label for="region_id"><?php echo $this->__('State / Province') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						
						<select id="region_id" name="region_id" class="validate-select" style="display:none;">
							<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
						</select>
						
						<script type="text/javascript">
							$('region_id').setAttribute('defaultValue',  "<?php echo $this->getFormData()->getRegionId() ?>");
						</script>
						
						<input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getRegion()) ?>" style="display:none;" />
					</li>
					
					<li>
						<label for="zip"><?php echo $this->__('Postal Code') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<input type="text" id="zip" name="postcode" value="<?php echo $this->htmlEscape($this->getFormData()->getPostcode()) ?>" class="validate-zip-international required-entry" />
					</li>
					
					<li>
						<label for="country"><?php echo $this->__('Country') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<?php echo $this->getCountryHtmlSelect() ?>
					</li>
				</ul>
				
				<input type="hidden" name="default_billing" value="1" />
				<input type="hidden" name="default_shipping" value="1" />
			<?php endif; ?>
		
			<h3><?php echo $this->__('Account Info') ?></h3>
			
			<ul class="struts">
				<li>
					<label for="email_address"><?php echo $this->__('Email') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="text" id="email_address" name="email" value="<?php echo $this->htmlEscape($this->getFormData()->getEmail()) ?>" class="validate-email required-entry" />
				</li>
				
				<li>
					<label for="password"><?php echo $this->__('Password') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="password" id="password" name="password" class="input-text required-entry validate-password" />
				</li>
				
				<li>
					<label for="confirmation"><?php echo $this->__('Confirm Password') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="password" id="confirmation" name="confirmation" class="input-text required-entry validate-cpassword" />
				</li>
				
				<?php if ($this->isNewsletterEnabled()): ?>
					<li>
						<input type="checkbox" id="is_subscribed" name="is_subscribed" value="1" <?php if($this->getFormData()->getIsSubscribed()): ?>checked="checked"<?php endif; ?> class="checkbox" />
						<label for="is_subscribed"><?php echo $this->__('Subscribe to the newsletter to receive store news and offers via email.') ?></label>
					</li>
				<?php endif ?>
				
				<?php echo $this->getChildHtml('persistent.remember.me'); ?>
			</ul>
			<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
			
			<button type="submit"><?php echo $this->__('Create My Account') ?></button>
			
			<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif; ?>
		</form>
		
		<script type="text/javascript">
		//<![CDATA[
			var dataForm = new VarienForm('register-form', true);
			<?php if($this->getShowAddressFields()): ?>
			new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
			<?php endif; ?>
		//]]>
		</script>
	</div>
	
	<div class="grid_4 prefix_1">
		<h2><?php echo $this->__('Already Have An Account?') ?></h2>
		<a class="faux-button" href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Log In') ?></a>
	</div>
</div>
