<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>

<?php $_productCollection = $this->getLoadedProductCollection() ?>
<?php if (!$_productCollection->count()): ?>
    <div class="catalog-bar">
        <?php
        /*
         * Set explicit position for breadcrumbs
         * @see /layout/catalog.xml
         * @see /template/page/gravdept_catalog-layered.phtml
         */
        echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
        ?>
    </div>

    <div class="catalog-no-results">
        <h2><?php echo $this->__('No items found.') ?></h2>

        <p><?php echo $this->__('Try searching or browse the categories.') ?></p>
    </div>
<?php else: ?>
    <div class="catalog-bar">
        <?php
        /*
         * Set explicit position for breadcrumbs
         * @see /layout/catalog.xml
         * @see /template/page/gravdept_catalog-layered.phtml
         */
        echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();
        ?>
        <a id="options-button">
            <span class="label">Vis alternativer<?php //echo $this->__('Show Options') ?></span>
            <span class="icon">...</span>
        </a>
        <div id="options-bar">
            <h2><?php echo $this->__('Options') ?></h2>
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>

    <?php if ($this->getMode() != 'grid'): /* List mode */ ?>
        <?php $_iterator = 0; ?>
        <ol class="product-list">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"/>
                    </a>
                    <div class="product-details">
                        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $this->htmlEscape($_product->getName()) ?>
                        </a>
                        <?php if ($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>
                        <p class="description"><?php echo nl2br($_product->getShortDescription()) ?></p>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </li>
            <?php endforeach; ?>
        </ol>

    <?php else: /* Grid Mode */ ?>
        <?php $_collectionSize = $_productCollection->count() ?>
        <table class="product-grid" cellspacing="0">
            <?php $_columnCount = $this->getColumnCount(); // Set number of columns from XML layout ?>
            <?php /* $_columnCount = 4; // Set number of columns here */ ?>
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>
                <td>
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>"/>
                    </a>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <a class="product-name" href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->htmlEscape($_product->getName()) ?>
                    </a>
                    <?php if ($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                </td>
            <?php endforeach ?>
            <?php for ($i; $i % $_columnCount != 0; $i++): ?>
                <td class="empty">&nbsp;</td>
            <?php endfor ?>
            <?php if ($i % $_columnCount == 0): ?>
                </tr>
            <?php endif ?>
        </table>
    <?php endif; ?>
    <div class="pager-bar">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>
