<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.0
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>

<script type="text/javascript">
	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>

<div class="block">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div id="product-header" class="grid">
	<div id="product-media" class="grid_5">
		<?php echo $this->getChildHtml('media') ?>
	</div>
	
	<div id="product-info" class="grid_7">
		<h1><?php echo $_helper->categoryAttribute($_product, $_product->getName(), 'name') ?></h1>
		
		<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
		
		<?php if ($_product->getShortDescription()):?>
			<p class="short-description"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>
		<?php endif; ?>
		
		<?php echo $this->getChildHtml('alert_urls') ?>
		
		<?php echo $this->getChildHtml('other')  /* reviews (return to product link) */ ?>
		
		<div class="grid">
			<div class="grid_5 alpha">
				<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
					<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
					<input type="hidden" name="related_product" id="related-products-field" value="" />		
					
					<?php echo $this->getChildHtml('tierprices') ?>
					
					<?php /* GravDept, move grouped product table outside "decision" block */ ?>
					<?php /*echo $this->getChildHtml('product_type_data_grouped')*/ ?>
					
					<?php if($_product->isSaleable()): ?>
						<div class="options">
							<?php /* quantity input */ ?>
							<?php echo $this->getChildHtml('addquantity') ?>
							
							<?php /* configurable options */ ?>
							<?php if ($this->hasOptions()):?>
								<?php echo $this->getChildChildHtml('container1', '', true, true) ?>
								<?php echo $this->getChildChildHtml('container2', '', true, true) ?>
							<?php endif; ?>
						</div>
					<?php endif; ?>
					
					<div class="decision">
						<?php /* price + availability + grouped */ ?>
						<?php echo $this->getChildHtml('product_type_data') ?>
						
						<?php if($_product->isSaleable()): ?>
							<?php echo $this->getChildHtml('addtocart') ?>
						<?php endif; ?>
					</div>
				</form>
				
				<script type="text/javascript">
					//<![CDATA[
						var productAddToCartForm = new VarienForm('product_addtocart_form');
						productAddToCartForm.submit = function(button, url) {
							if (this.validator.validate()) {
								var form = this.form;
								var oldUrl = form.action;
				
								if (url) {
								   form.action = url;
								}
								var e = null;
								try {
									this.form.submit();
								} catch (e) {
								}
								this.form.action = oldUrl;
								if (e) {
									throw e;
								}
				
								if (button && button != 'undefined') {
									button.disabled = true;
								}
							}
						}.bind(productAddToCartForm);
				
						productAddToCartForm.submitLight = function(button, url){
							if(this.validator) {
								var nv = Validation.methods;
								delete Validation.methods['required-entry'];
								delete Validation.methods['validate-one-required'];
								delete Validation.methods['validate-one-required-by-name'];
								if (this.validator.validate()) {
									if (url) {
										this.form.action = url;
									}
									this.form.submit();
								}
								Object.extend(Validation.methods, nv);
							}
						}.bind(productAddToCartForm);
					//]]>
				</script>
			</div>
			
			<div class="grid_2 omega">
				<ul class="product-actions">
					<?php echo $this->getChildHtml('addtowishlist') ?>
					
					<?php /*echo $this->getChildHtml('addtocompare')*/  /* removed from theme */ ?>
					
					<?php if ($this->canEmailToFriend()): ?>
						<li><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Share By Email') ?></a></li>
					<?php endif; ?>
				</ul>
				
				<ul class="social-share">
					<li class="twitter"><a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></li>
					<li class="googleplus">
					    <!-- Place this tag where you want the +1 button to render -->
					    <div class="g-plusone" data-size="medium"></div>
					    
					    <!-- Place this render call where appropriate -->
					    <script type="text/javascript">
					      (function() {
					        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
					        po.src = 'https://apis.google.com/js/plusone.js';
					        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
					      })();
					    </script>
					</li>
					<li class="facebook"><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" send="false" layout="button_count" width="130" show_faces="false" font=""></fb:like></li>
				</ul>
			</div>
		</div>
		
	</div>
</div>

<div class="grid">
	<div class="grid_5">
		<?php echo $this->getChildHtml('related_products') ?>
		&nbsp;<!-- placeholder if no related items -->
	</div>

	<div class="grid_7">
		<?php if ($_description = $this->getChildHtml('description')):?>
			<?php echo $_description ?>
		<?php endif; ?>
		
		<?php if ($_attributes = $this->getChildHtml('product_attributes')):?>
			<?php echo $_attributes ?>
		<?php endif; ?>
		
		<?php echo $this->getChildHtml('product_additional_data')  /* tags */ ?>
	</div>
</div>

<?php echo $this->getChildHtml('upsell_products') ?>

<div class="grid">
	<div class="grid_6">
		<div class="callout">
			<?php echo $this->getChildHtml('product_reviews') ?>
		</div>
	</div>
	
	<div class="grid_6">
		<div class="callout">
			<?php echo $this->getChildHtml('product_review_form') ?>
		</div>
	</div>
</div>
