<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.7
 */
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="grid">
	<div class="grid_4 alpha">
		<h3><?php echo $this->__('Sign In') ?></h3>
		
		<form id="login-form" class="simple" action="<?php echo $this->getPostAction() ?>" method="post">
			<ul class="struts">
				<li>
					<label for="login-email"><?php echo $this->__('Email') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="text" class="required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
				</li>
				<li>
					<label for="login-password"><?php echo $this->__('Password') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="password" class="required-entry" id="login-password" name="login[password]" />
				</li>
			</ul>
			
			<button type="submit"><?php echo $this->__('Sign In') ?></button>
			<a class="alt-action" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
		</form>
	</div>

	<div class="grid_3 omega">
		<h3><?php echo $this->__('Don\'t Have An Account?') ?></h3>
		
		<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
			<ul class="formless-struts">
				<li>
					<input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> />
					<label for="login:register"><?php echo $this->__('Sign up and checkout together') ?></label>
				
					<?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
						<input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Sales_Model_Quote::CHECKOUT_METHOD_GUEST): ?> checked="checked"<?php endif; ?> />
						<label for="login:guest"><?php echo $this->__('Checkout as a guest (account not required)') ?></label>
					<?php endif; ?>
				</li>
			</ul>
		<?php else: ?>
			<input type="hidden" name="checkout_method" id="login:register" value="register" />
		<?php endif; ?>
		
		<button onclick="checkout.setMethod();"><?php echo $this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Create An Account') ?></button>
	</div>
</div>

<script type="text/javascript">
	var loginForm = new VarienForm('login-form', true);
</script>
