<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.5
 */
?>

<div id="opc-progress" class="callout opc-block-progress">
	<h2><?php echo $this->__('Progress') ?></h2>
	
	<dl class="opc-progress-list">
		<?php if ($this->getCheckout()->getStepData('billing', 'is_show')): ?>
			<?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
				<dt class="complete">
					<?php echo $this->__('Billing Information') ?> <a href="#billing" onclick="checkout.accordion.openSection('opc-billing'); return false;"><?php echo $this->__('Edit') ?></a>
				</dt>
				<dd class="complete">
					<p class="address-book-entry"><?php echo $this->getBilling()->format('html') ?></p>
				</dd>
			<?php else: ?>
				<dt class="incomplete"><?php echo $this->__('Billing Information') ?> <span><?php echo $this->__('Pending') ?></span></dt>
			<?php endif; ?>
		<?php endif; ?>
	
		<?php if ($this->getCheckout()->getStepData('shipping', 'is_show')): ?>
			<?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
				<dt class="complete">
					<?php echo $this->__('Shipping Information') ?> <a href="#shipping" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Edit') ?></a>
				</dt>
				<dd class="complete">
					<p class="address-book-entry"><?php echo $this->getShipping()->format('html') ?></p>
				</dd>
			<?php else: ?>
				<dt class="incomplete"><?php echo $this->__('Shipping Information') ?> <span><?php echo $this->__('Pending') ?></span></dt>
			<?php endif; ?>
		<?php endif; ?>
	
		<?php if ($this->getCheckout()->getStepData('shipping_method', 'is_show')): ?>
			<?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
				<dt class="complete">
					<?php echo $this->__('Shipping Method') ?> <a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method'); return false;"><?php echo $this->__('Edit') ?></a>
				</dt>
				<dd class="complete">
					<?php if ($this->getShippingMethod()): ?>
						<?php echo $this->getShippingDescription() ?>
		
						<?php $_excl = $this->getShippingPriceExclTax(); ?>
						<?php $_incl = $this->getShippingPriceInclTax(); ?>
						
						<?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
							<?php echo $_incl; ?>
						<?php else: ?>
							<?php echo $_excl; ?>
						<?php endif; ?>
						
						<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
							(<?php echo $this->__('Incl. Tax') ?> <?php echo $_incl; ?>)
						<?php endif; ?>
					<?php else: ?>
						<?php echo $this->__('Shipping method hasn\'t been selected yet.') ?>
					<?php endif; ?>
				</dd>
			<?php else: ?>
				<dt class="incomplete"><?php echo $this->__('Shipping Method') ?> <span><?php echo $this->__('Pending') ?></span></dt>
			<?php endif; ?>
		<?php endif; ?>
	
		<?php if ($this->getCheckout()->getStepData('payment', 'is_show')): ?>
			<?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
				<dt class="complete">
					<?php echo $this->__('Payment Method') ?> <a href="#payment" onclick="checkout.accordion.openSection('opc-payment'); return false;"><?php echo $this->__('Edit') ?></a>
				</dt>
				<dd class="complete">
					<?php echo $this->getPaymentHtml() ?>
				</dd>
			<?php else: ?>
				<dt class="incomplete"><?php echo $this->__('Payment Method') ?> <span><?php echo $this->__('Pending') ?></span></dt>
			<?php endif; ?>
		<?php endif; ?>
	</dl>
</div>
