<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<form id="co-shipping-form" class="simple" action="">

	<input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
	
	<?php if ($this->customerHasAddresses()): ?>
		<ul class="struts">
			<li>
				<label for="shipping-address-select"><?php echo $this->__('Select from your address book or create a new address') ?></label>
				<?php echo $this->getAddressesHtmlSelect('shipping') ?>
			</li>
		</ul>
	<?php endif ?>
	
	<ul class="struts" id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>

		<?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
		<?php /*
		<li>
			<label for="shipping:company"><?php echo $this->__('Company') ?></label>
			<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" onchange="shipping.setSameAsBilling(false);" />
		</li>
		*/ ?>
		<li>
			<label for="shipping:street1"><?php echo $this->__('Street') ?> 1 <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="required-entry" onchange="shipping.setSameAsBilling(false);" />
		</li>
		
		<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
			<li>
				<label for="shipping:street<?php echo $_i ?>"><?php echo $this->__('Street') ?> <?php echo $_i ?></label>
				<input type="text" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" onchange="shipping.setSameAsBilling(false);" />
			</li>
		<?php endfor ?>
		
		<li>
			<label for="shipping:city"><?php echo $this->__('City') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="required-entry" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
		</li>
		
		<li>
			<label for="shipping:region"><?php echo $this->__('State/Province') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			
			<select id="shipping:region_id" name="shipping[region_id]" class="validate-select" style="display:none;">
				<option value=""><?php echo $this->__('Please select state, region, or province') ?></option>
			</select>
			
			<script type="text/javascript">
				$('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
			</script>
			
			<input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" style="display:none;" />
		</li>
		
		<li>
			<label for="shipping:postcode"><?php echo $this->__('Postal Code') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="validate-zip-international required-entry" onchange="shipping.setSameAsBilling(false);" />
		</li>
		
		<li>
			<label for="shipping:country_id"><?php echo $this->__('Country') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<?php echo $this->getCountryHtmlSelect('shipping') ?>
		</li>
		
		<li>
			<label for="shipping:telephone"><?php echo $this->__('Phone') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" class="required-entry" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
		</li>
		
		<?php /*
		<li>
			<label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
			<input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
		</li>
		*/ ?>
		
		<li>
			<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
				<input type="checkbox" name="shipping[save_in_address_book]" value="1" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> />
				<label for="shipping:save_in_address_book"><?php echo $this->__('Save in my address book') ?></label>
			<?php else: ?>
				<input type="hidden" name="shipping[save_in_address_book]" value="1" />
			<?php endif; ?>
			
			<input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> onclick="shipping.setSameAsBilling(this.checked)" />
			<label for="shipping:same_as_billing"><?php echo $this->__('Nevermind, ship to my billing address instead') ?></label>
		</li>
		
	</ul>

	<div id="shipping-buttons-container">
		<button onclick="shipping.save()"><?php echo $this->__('Continue') ?></button>
		<span id="shipping-please-wait" class="opc-ajax-loading" style="display:none;"><?php echo $this->__('Loading') ?></span>
	</div>

</form>

<script type="text/javascript">
	//<![CDATA[
		var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
			'<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
		var shippingForm = new VarienForm('co-shipping-form');
		shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
		//shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
		$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
	
		var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions);
	//]]>
</script>
