<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.5
 */
?>
<?php
/**
 * Multishipping checkout shipping template
 *
 * @see Mage_Checkout_Block_Multishipping_Shipping
 */
?>

<h1><?php echo $this->__('Shipping Information') ?></h1>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form id="shipping_method_form" class="simple" action="<?php echo $this->getPostActionUrl() ?>" method="post">
	<?php foreach ($this->getAddresses() as $_index => $_address): ?>
		<div class="grid callout multiship-address-group">
			<h2><?php echo $this->__('Address %s of %s', ($_index+1), $this->getAddressCount()) ?></h2>
			
			<div class="grid_4 alpha">
				<div class="liner">
					<h3><?php echo $this->__('Shipping Method') ?></h3>
					
					<?php if (!($_shippingRateGroups = $this->getShippingRates($_address))): ?>
						<p><?php echo $this->__('Sorry, no shipping quotes are available for your order at this time.') ?></p>
					<?php else: ?>
						<dl class="sp-methods">
							<?php $_sole = count($_shippingRateGroups) == 1; ?>
							<?php foreach ($_shippingRateGroups as $code => $_rates): ?>
								<dt><?php echo $this->getCarrierName($code) ?></dt>
								<dd>
									<ul>
										<?php $_sole = $_sole && count($_rates) == 1; ?>
										<?php foreach ($_rates as $_rate): ?>
											<li<?php if ($_rate->getErrorMessage()) echo ' class="error-msg"' ?>>
											   <?php if ($_rate->getErrorMessage()): ?>
													<?php echo $_rate->getCarrierTitle() ?>: <?php echo $_rate->getErrorMessage() ?>
											   <?php else: ?>
													<?php if ($_sole) : ?>
														<span class="no-display"><input type="radio" name="shipping_method[<?php echo $_address->getId() ?>]" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>" checked="checked"/></span>
													<?php else: ?>
														<input type="radio" name="shipping_method[<?php echo $_address->getId() ?>]" value="<?php echo $this->htmlEscape($_rate->getCode()) ?>" id="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod($_address)) echo ' checked="checked"' ?> class="radio" />
													<?php endif; ?>
													
													<label for="s_method_<?php echo $_address->getId() ?>_<?php echo $_rate->getCode() ?>"><?php echo $_rate->getMethodTitle() ?>
														<?php $_excl = $this->getShippingPrice($_address, $_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
														<?php $_incl = $this->getShippingPrice($_address, $_rate->getPrice(), true); ?>
														<?php echo $_excl; ?>
														
														<?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
															(<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
														<?php endif; ?>
													</label>
											   <?php endif ?>
											</li>
										<?php endforeach; ?>
									</ul>
								</dd>
							<?php endforeach; ?>
						</dl>
					<?php endif; ?>
				</div>
			</div>

			<div class="grid_3">
				<h3><?php echo $this->__('Destination') ?></h3>
				<?php /*<a href="<?php echo $this->getAddressEditUrl($_address) ?>"><?php echo $this->__('Edit Address') ?></a>*/ ?>
				<p class="address-entry"><?php echo $_address->format('html') ?></p>
			</div>

			<div class="grid_5 omega">
				<?php echo $this->helper('giftmessage/message')->getInline('multishipping_adress_checkbox', $_address); ?>
				
				<h3><?php echo $this->__('Items') ?></h3>
				<?php /*<a href="<?php echo $this->getItemsEditUrl($_address) ?>"><?php echo $this->__('Edit Items') ?></a>*/ ?>
				
				<table id="shipping-table-<?php echo $_address->getId() ?>" class="simple">
					<thead>
						<tr>
							<th><abbr title="<?php echo $this->__('Quantity') ?>"><?php echo $this->__('Qty.') ?></abbr></th>
							<th><?php echo $this->__('Product') ?></th>
						</tr>
					</thead>
					
					<tbody>
						<?php foreach ($this->getAddressItems($_address) as $_item): ?>
							<tr>
								<td><?php echo $_item->getQty() ?></td>
								<td class="width-full"><?php echo $this->getItemHtml($_item->getQuoteItem()) ?></td>
							</tr>
						<?php endforeach; ?>
					</tbody>
				</table>
			</div>
			
			<div class="grid_12 alpha omega">
				<div class="liner">
					<?php echo $this->helper('giftmessage/message')->getInline('multishipping_adress', $_address); ?>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
	
	<?php echo $this->getChildHtml('checkout_billing_items') ?>
	
	<div class="multiship-actions">
		<a class="faux-button" href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('Go Back') ?></a>
		<button type="submit"><?php echo $this->__('Continue') ?></button>
	</div>
</form>
