<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.0
 */
?>

<div class="block">
	<h1><?php echo $this->__('Forgot Password') ?></h1>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
</div>

<div class="grid">	
	<div class="grid_6">
		<p><?php echo $this->__('Please enter your email address below. We will send you a link to reset your password.') ?></p>

		<form id="forgot-password-form" class="simple" action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post">
			<ul class="struts">
				<li>
					<label for="email_address"><?php echo $this->__('Email') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
					<input type="text" id="email_address" name="email" class="required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
				</li>
			</ul>
	
			<button type="submit"><?php echo $this->__('Reset Password') ?></button>		
		</form>
		
		<script type="text/javascript">
			//<![CDATA[
				var dataForm = new VarienForm('forgot-password-form', true);
			//]]>
		</script>
	</div>
</div>
