<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.0
 */
?>

<div class="block">
	<h1><?php echo $this->__('Reset Password'); ?></h1>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml(); ?>
	
	<form id="reset-password-form" class="simple" action="<?php echo $this->getUrl('*/*/resetpasswordpost', array('_query' => array('id' => $this->getCustomerId(), 'token' => $this->getResetPasswordLinkToken()))); ?>" method="post">
		<ul class="struts">
			<li>
				<label for="password" class="required"><?php echo $this->__('New Password') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
				<input type="password" class="input-text required-entry validate-password" name="password" id="password" />
			</li>
			
			<li>
				<label for="confirmation" class="required"><?php echo $this->__('Confirm New Password') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
				<input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
			</li>
		</ul>
	
		<button type="submit"><?php echo $this->__('Reset Password'); ?></button>
	</form>
	
	<script type="text/javascript">
	/*<![CDATA[*/
		var dataForm = new VarienForm('reset-password-form', true);
	/*]]>*/
	</script>
</div>
