<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.1
 */
?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
	<h1><?php echo $this->__('My Wishlist') ?></h1>
	
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<?php /*
	<?php if($this->helper('wishlist')->isRssAllow() && $this->getWishlist()->getSize()): ?>
		<a href="<?php echo $this->helper('wishlist')->getRssUrl(); ?>">RSS Feed</a>
	<?php endif; ?>
	*/ ?>
	
	<?php if($this->hasWishlistItems()): ?>
	
		<form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
			<?php echo $this->getBlockHtml('formkey')?>
			
			<table id="wishlist-table" class="flex" cellspacing="0">
				<thead>
					<tr>
						<th class="remove"><?php echo $this->__('Remove') ?></th>
						<th colspan="2"><?php echo $this->__('Product Info') ?></th>
						<th><?php echo $this->__('Notes') ?></th>
						<th><?php echo $this->__('Purchase') ?></th>
					</tr>
				</thead>
				
				<tfoot>
					<tr>
						<td colspan="3">&nbsp;</td>
						
						<td>
							<button type="submit" name="do"><?php echo $this->__('Save my wishlist') ?></button>
						</td>
						
						<td>
							<?php if($this->isSaleable()):?>
								<a class="faux-button" onclick="addAllWItemsToCart()"><?php echo $this->__('Add wishlist to cart') ?></a>
							<?php endif;?>
						</td>
					</tr>
				</tfoot>
				
				<tbody>
					<?php foreach($this->getWishlistItems() as $item): ?>
						<?php
						$product = $item->getProduct();
						$isVisibleProduct = $product->isVisibleInSiteVisibility();
						?>
						
						<tr>
							<td><a class="btn-remove" href="<?php echo $this->getItemRemoveUrl($item) ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo $this->__('Remove from wishlist') ?>"><?php echo $this->__('Remove from wishlist') ?></a></td>
							
							<td>
								<a class="product-image" href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>">
									<img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(50); ?>" alt="<?php echo $this->escapeHtml($product->getName()) ?>" />
								</a>
							</td>
							
							<td class="width-full">
								<a href="<?php echo $this->getProductUrl($item) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a>
								
								<?php echo $this->getPriceHtml($product) ?>
								<?php echo $this->getDetailsHtml($item) ?>
								
								<div class="date-added">
									<?php echo $this->__('Added') ?>
									
									<?php /* Magento, original */ ?>
									<?php /*echo $this->getFormatedDate($item->getAddedAt())*/ ?>
									
									<?php /* GravDept, custom */ ?>
									<?php echo date( 'F j, Y', strtotime( $this->getFormatedDate($item->getAddedAt()) ) ) ?>
									
									<?php
									/* GravDept, other date format options in Magento. They don't seem to work. */
									/*
									<?php echo $this->getFormatedDate($item->getAddedAt(), 'full') ?>
									<?php echo $this->getFormatedDate($item->getAddedAt(), 'medium') ?>
									<?php echo $this->getFormatedDate($item->getAddedAt(), 'long') ?>
									<?php echo $this->getFormatedDate($item->getAddedAt(), 'short') ?>
									*/
									?>
								</div>
							</td>
							
							<td><textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="2" onfocus="focusComment(this)" onblur="focusComment(this)"><?php echo $this->getCommentValue($item); ?></textarea></td>
							
							<td>
								<?php if ($item->canHaveQty() && $isVisibleProduct): ?>
									<div class="wishlist-qty">
										<label for="qty[<?php echo $item->getId() ?>]"><?php echo $this->__('Quantity') ?></label>
										<input type="text" class="qty" name="qty[<?php echo $item->getId() ?>]" id="qty[<?php echo $item->getId() ?>]" value="<?php echo $this->getAddToCartQty($item) * 1 ?>" />
									</div>
								<?php endif; ?>
								
								<?php if ($product->isSaleable()): ?>
									<?php if ($isVisibleProduct): ?>
										<button type="button" onclick="addWItemToCart(<?php echo $item->getId(); ?>)" class="button"><?php echo $this->__('Add To Cart') ?></button>
									<?php endif; ?>
								<?php else: ?>
									<p class="availability out-of-stock"><?php echo $this->__('Out Of Stock') ?></p>
								<?php endif; ?>
								
								<?php /* GravDept, hide redundant link to product view */ ?>
								<?php /*if ($isVisibleProduct): ?>
									<p><a href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a></p>
								<?php endif;*/ ?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</form>
		
		<?php /* GravDept, hidden */ ?>
		<?php /*<button type="submit" onclick="this.name='save_and_share'" class="button"><?php echo $this->__('Share Wishlist') ?></button>*/ ?>
		
	<?php else: ?>
	
		<p><?php echo $this->__('Your wishlist is empty.') ?></p>
	
	<?php endif; ?>
	
	
	<script type="text/javascript">
		//<![CDATA[
		function confirmRemoveWishlistItem() {
			return confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>');
		}
		
		function focusComment(obj) {
			if( obj.value == '<?php echo $this->helper('wishlist')->defaultCommentString() ?>' ) {
				obj.value = '';
			} else if( obj.value == '' ) {
				obj.value = '<?php echo $this->helper('wishlist')->defaultCommentString() ?>';
			}
		}
		
		function addWItemToCart(itemId) {
	        var url = '<?php echo $this->getItemAddToCartUrl('%item%') ?>';
	        url = url.gsub('%item%', itemId);
	        var form = $('wishlist-view-form');
	        if (form) {
	            var input = form['qty[' + itemId + ']'];
	            if (input) {
	                var separator = (url.indexOf('?') >= 0) ? '&' : '?';
	                url += separator + input.name + '=' + encodeURIComponent(input.value);
	            }
	        }
	        setLocation(url);
	    }
	
	    function addAllWItemsToCart() {
	        var url = '<?php echo $this->getUrl('*/*/allcart') ?>';
	        var separator = (url.indexOf('?') >= 0) ? '&' : '?';
	        $$('#wishlist-view-form .qty').each(
	            function (input, index) {
	                url += separator + input.name + '=' + encodeURIComponent(input.value);
	                separator = '&';
	            }
	        );
	        setLocation(url);
	    }
		//]]>
	</script>
<?php endif; ?>