<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.0
 */
?>

<div id="tags" class="callout">
	<h2><?php echo $this->__('Tags') ?></h2>
	
	<div class="grid">
		<div class="grid_4 alpha">
			<form id="add-tag-form" class="simple" action="<?php echo $this->getFormAction(); ?>" method="get">
				<ul class="struts">
					<li>
						<label for="productTagName"><?php echo $this->__('Add Tags') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
						<input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
					</li>
				</ul>
				
				<button type="submit" onclick="submitTagForm()"><?php echo $this->__('Add Tags') ?></button>
			</form>
			
			<p class="hint"><?php echo $this->__('Separate tags with spaces. Wrap multi-word tags in single quotes. Example: \'New York\' Manhattan') ?></p>
		</div>
		
		<div class="grid_3 omega">
			<?php echo $this->getChildHtml('list_before')?>
			
			<?php if( $this->getCount() ): ?>
				<ul class="product-tags">
					<?php foreach( $this->getTags() as $_tag ): ?>
						<li>
							<a href="<?php echo $_tag->getTaggedProductsUrl() ?>">
								<span class="count"><?php echo $_tag->getPopularity() ?></span>
								<span class="tag"><?php echo $this->htmlEscape($_tag->getName()) ?></span>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
	</div>
	
	<script type="text/javascript">
		//<![CDATA[
			var addTagFormJs = new VarienForm('add-tag-form');
			function submitTagForm(){
				if(addTagFormJs.validator.validate()) {
					addTagFormJs.form.submit();
				}
			}
		//]]>
	</script>
</div>
