<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.9
 */
?>

<?php $_product = $this->getProduct() ?>

<?php if($_product->isSaleable()): ?>

	<?php if(!$_product->isGrouped()): ?>
		<div class="product-qty">
    		<label for="qty"><?php echo $this->__('Quantity') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
    		
    		<?php /* GravDept, fixes default qty bug */ ?>
    		<?php /*<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" class="input-text qty" />*/ ?>
    		<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product)== null?1:$this->getMinimalQty($_product) ?>" class="input-text qty" />
		</div>
	<?php endif; ?>

<?php endif; ?>
