<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.5
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>

<?php if($_product->isSaleable()): ?>
	<div class="add-to-cart">
		<?php /* GravDept, quantity form was moved to: /catalog/product/view/addquantity.phtml */ ?>
		<?php /*
		<?php if(!$_product->isGrouped()): ?>
			<label for="qty"><?php echo $this->__('Qty:') ?></label>
			<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
		<?php endif; ?>
		*/ ?>
		
		<button type="button" onclick="productAddToCartForm.submit(this)"><?php echo $buttonTitle ?></button>
		
		<?php echo $this->getChildHtml('', true, true) ?>
	</div>
<?php endif; ?>