<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<?php $_product = $this->getProduct() ?>

<?php if ($this->helper('wishlist')->isAllow()) : ?>
	<li class="add-to-wishlist">
		<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add To Wishlist') ?></a>
		<?php /*<span><?php echo $this->__('Save a reminder for later') ?></span>*/ ?>
	</li>
<?php endif; ?>
