<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>

<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>

<?php if($_additional = $this->getAdditionalData()): ?>
	<div class="callout">
		<h2><?php echo $this->__('Details') ?></h2>
		
		<table id="attributes-table" cellspacing="0">
			<tbody>
				<?php foreach ($_additional as $_data): ?>
					<tr>
						<th><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
						<td><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
<?php endif;?>
