<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.3.1
 */
?>
<?php 
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>

<?php $_menu = '' ?>

<?php foreach ($this->getStoreCategories() as $_category): ?>
	<?php $_menu .= $this->drawItem($_category) ?>
<?php endforeach ?>
<?php if ($_menu): ?>
	<?php $_menu = str_replace('Vis alle', 'Vis mer', $_menu) ?>
	<ul id="nav">
	    <!--<li class="level0 nav-home"><a href="<?php echo $this->getUrl() ?>"><?php echo $this->__('Home') ?></a></li>-->
		<?php echo $_menu; ?>
	</ul>
<?php endif; ?>
