<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Template for filter items block
 *
 * @see Mage_Catalog_Block_Layer_Filter
 */
?>

<ol>
	<?php foreach ($this->getItems() as $_item): ?>
		<li>
			<a href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
				<span class="count"><?php echo $_item->getCount() ?></span>
				<?php echo $_item->getLabel() ?>
			</a>
		</li>
	<?php endforeach ?>
</ol>
