<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>

<?php if($this->canShowBlock()): ?>

	<div id="filter" class="callout">
		<h2><?php echo $this->__('Filter By') ?></h2>
		
		<div class="filters">
			<?php /* active */ ?>
			<?php echo $this->getStateHtml() ?>
		
			<?php if($this->canShowOptions()): ?>
				<dl class="inactive">
					<?php $_filters = $this->getFilters() ?>
					<?php foreach ($_filters as $_filter): ?>
						<?php if($_filter->getItemsCount()): ?>
							<dt><?php echo $this->__($_filter->getName()) ?></dt>
							<dd><?php echo $_filter->getHtml() ?></dd>
						<?php endif; ?>
					<?php endforeach; ?>
				</dl>
			<?php endif; ?>
		</div>
	</div>
	
<?php endif; ?>
