<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.4
 */
?>

<?php /* @var $this Mage_Catalog_Block_Product_View_Abstract */?>
<?php $_product = $this->getProduct() ?>

<?php if ($_product->isAvailable()): ?>
	<div class="availability in-stock"><?php echo $this->__('In Stock') ?></div>
<?php else: ?>
	<div class="availability out-of-stock"><?php echo $this->__('Utsolgt') ?></div>
<?php endif; ?>


<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php echo $this->getPriceHtml($_product) ?>
