<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.8
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>

<?php if($this->getTitle()): ?>
	<h1><?php echo $this->getTitle() ?></h1>
<?php else: ?>
	<h1><?php echo $this->__('Address Entry') ?></h1>
<?php endif; ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form id="edit-address-form" class="scaffold" action="<?php echo $this->getSaveUrl() ?>" method="post">

	<?php echo $this->getBlockHtml('formkey')?>

	<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
	<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

	<h3><?php echo $this->__('Contact Info') ?></h3>
	
	<ul class="struts">
		<?php echo $this->getNameBlockHtml() ?>
		
		<?php /*<li>
			<label for="company"><?php echo $this->__('Company') ?></label>
			<input type="text" name="company" id="company" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" />
		</li>*/ ?>
		
		<li>
			<label for="telephone"><?php echo $this->__('Phone') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" id="telephone" name="telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" class="required-entry" />
		</li>
		
		<?php /*
		<li>
			<label for="fax"><?php echo $this->__('Fax') ?></label>
			<input type="text" name="fax" id="fax" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" />
		</li>
		*/ ?>
	</ul>
	
	<h3><?php echo $this->__('Address') ?></h3>
	
	<ul class="struts">
		<li>
			<label for="street_1"><?php echo $this->__('Street') ?> 1 <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" id="street_1" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="required-entry" />
		</li>
		
		<?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
			<li>
				<label for="street_<?php echo $_i ?>"><?php echo $this->__('Street') ?> <?php echo $_i ?></label>
				<input type="text" id="street_<?php echo $_i ?>" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" />
			</li>
		<?php endfor ?>
		
		<li>
			<label for="city"><?php echo $this->__('City') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" id="city" name="city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="required-entry" />
		</li>
		
		<li>
			<label for="region_id"><?php echo $this->__('State / Province') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<select id="region_id" name="region_id" class="validate-select" style="display:none;">
			   <option value=""><?php echo $this->__('Please select state, region, or province') ?></option>
			</select>
			<script type="text/javascript">
				$('region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
			</script>
			<input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" />
		</li>
		
		<li>
			<label for="zip"><?php echo $this->__('Postal Code') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" id="zip" class="validate-zip-international required-entry" />
		</li>
		
		<li>
			<label for="country"><?php echo $this->__('Country') ?> <abbr title="<?php echo $this->__('Required') ?>">*</abbr></label>
			<?php echo $this->getCountryHtmlSelect() ?>
		</li>
		
		<li>
			<?php if($this->isDefaultBilling()): ?>
				<p class="default-address"><?php echo $this->__('This is your primary billing address.') ?></p>
			<?php elseif($this->canSetAsDefaultBilling()): ?>
				<input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox" />
				<label for="primary_billing"><?php echo $this->__('Make this my default billing address.') ?></label>
			<?php else: ?>
				<input type="hidden" name="default_billing" value="1" />
				<p class="default-address"><?php echo $this->__('This will be your default billing address.') ?></p>
			<?php endif; ?>
		</li>
		
		<li>
			<?php if($this->isDefaultShipping()): ?>
				<p class="default-address"><?php echo $this->__('This will be your default shipping address.') ?></p>
			<?php elseif($this->canSetAsDefaultShipping()): ?>
				<input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox" />
				<label for="primary_shipping"><?php echo $this->__('Make this my default shipping address.') ?></label>
			<?php else: ?>
				<input type="hidden" name="default_shipping" value="1" />
				<p class="default-address"><?php echo $this->__('This will be your default shipping address.') ?></p>
			<?php endif; ?>
		</li>

	</ul>
	
	<button type="submit"><?php echo $this->__('Save Address') ?></button>
</form>

<script type="text/javascript">
	//<![CDATA[
		var dataForm = new VarienForm('edit-address-form', true);
		new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
	//]]>
</script>
