<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.0.0
 */
?>

<?php echo $this->getChildHtml('', true, true);?>

<?php /*
<?php if ($this->hasRequiredOptions()):?>
	<p><abbr>*</abbr> Required</p>
<?php endif;?>
*/ ?>
