<img src='//cdn.klarna.com/public/images/SE/logos/v1/basic/SE_basic_logo_std_blue-black.png?height=44&width=155' border='0' />
<?php if (isset($showTransactionNumber)): ?>
<p><b><?php echo $label; ?>:</b> <?php echo $transactionNumber; ?></p>
<?php endif; ?>
<?php if (isset($showInvoiceNumbers)): ?>
<fieldset>
    <ul>
        <li><b><?php echo $invoiceLabel; ?></b></li>
        <?php foreach($invoiceNumbers as $link): ?>
        <li><?php echo $link; ?></li>
        <?php endforeach; ?>
    </ul>
</fieldset>
<?php endif; ?>
