<?php
/**
 * Acumen for Magento
 * http://gravitydept.com/to/acumen-magento
 *
 * @author     Brendan Falkowski
 * @package    gravdept_acumen
 * @copyright  Copyright 2011 Gravity Department http://gravitydept.com
 * @license    All rights reserved.
 * @version    1.2.5
 */
?>

<?php /* @var $this Mage_Bundle_Block_Catalog_Product_View_Type_Bundle_Option_Select */ ?>
<?php $_option      = $this->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $this->_getDefaultValues(); ?>

<dt>
	<label<?php if ($_option->getRequired()) echo ' class="required"' ?>>
		<?php echo $this->htmlEscape($_option->getTitle()) ?>
		
		<?php if ($_option->getRequired()): ?>
			<abbr title="<?php echo $this->__('Required') ?>">*</abbr>
		<?php endif; ?>
	</label>
</dt>

<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
	<span class="qty-holder">
		<label for="bundle-option-<?php echo $_option->getId() ?>-qty-input"><abbr title="<?php echo $this->__('Quantity') ?>"><?php echo $this->__('Qty.') ?></abbr></label>
		<input onkeyup="bundle.changeOptionQty(this, event)" onblur="bundle.changeOptionQty(this, event)" <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?> id="bundle-option-<?php echo $_option->getId() ?>-qty-input" class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>" type="text" name="bundle_option_qty[<?php echo $_option->getId() ?>]" value="<?php echo $_defaultQty ?>"/>
	</span>
	
	<?php if ($this->_showSingle()): ?>
		<?php echo $this->getSelectionTitlePrice($_selections[0]) ?>
		<input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
	<?php else: ?>
		<select onchange="bundle.changeSelection(this)" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]" class="bundle-option-<?php echo $_option->getId() ?><?php if ($_option->getRequired()) echo ' required-entry' ?> bundle-option-select change-container-classname">
			<option value=""><?php echo $this->__('Choose a selection...') ?></option>
			
			<?php foreach ($_selections as $_selection): ?>
				<option value="<?php echo $_selection->getSelectionId() ?>"<?php if ($this->_isSelected($_selection)) echo ' selected="selected"' ?><?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>><?php echo $this->getSelectionTitlePrice($_selection, false) ?></option>
			<?php endforeach; ?>
		</select>
	<?php endif; ?>
</dd>
