<!--
/**
 * Klarna
 * JavaScript includes for OneStepCheckout
*/
-->
<link type="text/css" rel="stylesheet" href="//cdn.klarna.com/public/kitt/res/v1.1/images.css" />
<script src="//cdn.klarna.com/public/kitt/core/v1.0/js/klarna.min.js" type="text/javascript"></script>
<script src="//cdn.klarna.com/public/kitt/toc/v1.1/js/klarna.terms.min.js" type="text/javascript" charset="utf-8"></script>
<script src="//cdn.klarna.com/public/kitt/letop/v1.0/js/klarna.letop.js" type="text/javascript" charset="utf-8"></script>
<script src="//cdn.klarna.com/public/kitt/res/v1.1/js/klarna.lib.js" type="text/javascript"></script>
<script src="//cdn.klarna.com/public/kitt/res/v1.1/js/checkout.js" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>klarnaosc.js" type="text/javascript"></script>
